Afficher les plats depuis la BDD, tout simplement
WildCodeSchool/orleans-0219-php-dionysos pull request #41
Opened 2019-04-23 15:17 UTC by heagerty

Afficher les plats depuis la BDD, tout simplement

2019-04-23 15:45 UTC, dimxpas approved these changes

2019-04-24 07:25 UTC, sblondeau requested changes

2019-04-24 07:25 UTC, sblondeau commented on src/Controller/DishController.php
> +    public function show(int $id)
ta US est d'afficher les plats du restaurant pour un visiteur, donc que l'index, pas de show, edit, add ou delete

2019-04-24 07:25 UTC, sblondeau commented on src/Model/DishManager.php
> +    public function insert(array $dish): int
idem ici toutes ces méthodes sont en trop.
Tu dois faire 5 US (donc 5 PR différentes), une pour lister les plats (c'est celle-ci)
- une pour afficher un seul plat, 
- une pour ajouter un plat
- une pour editer un plat
- une pour supprimer un plat

2019-04-24 14:11 UTC, closed without merging