Sprint03 us24 structure reservation
WildCodeSchool/orleans-0219-php-dionysos pull request #51
Opened 2019-04-26 09:16 UTC by dimxpas

2019-04-26 09:30 UTC, heagerty approved these changes
apprové, comme demandé

2019-04-26 15:02 UTC, heagerty approved these changes
OK. Beaucoup de fichiers, mais aucun problème saute aux yeux.

2019-04-28 21:37 UTC, sblondeau requested changes
plein de petites choses à revoir
Faire attention de ne pas modifier (et commiter) des fichiers qui ne font pas partie de ceux que tu dois modifier pour ta US

2019-04-28 21:37 UTC, sblondeau commented on .gitignore
> +composer.lock
bah non !!! reprends le cours sur Git, le composer.lock DOIT être versionné !

2019-04-28 21:37 UTC, sblondeau commented on src/Controller/ReservationController.php
> +    private function checkErrors(array $cleanPost): array
il faut aller plus loin que de vérifier empty ou non sur les erreurs
- l'email avec un filter_var
- la date si elle est à un format de date existante (voir si elle est bien >= à today; ça semble pertinent pour une résa)
- nbPeople bien entre 0 et MAX_PEOPLE (22 de memoire)
- appointment que c'est bien un format d'horaire...

2019-04-28 21:37 UTC, sblondeau commented on src/Controller/ReservationController.php
> +                $reservation = [
en fait $reservation = $cleanPost non ? pas la pein de faire plus compliqué ?

2019-04-28 21:37 UTC, sblondeau commented on src/Controller/ReservationController.php
> +                header('Location:/Reservation/success');
il faut tjs mettre un exit() après un header(Location) 
https://www.php.net/manual/fr/function.header.php

2019-04-28 21:37 UTC, sblondeau commented on src/View/base.html.twig
ce fichier ne devrait pas etre modifié pour cette PR (d'autant qu'ici les modifs sont des retours à la ligne supplémentaires et inutiles

2019-04-28 21:37 UTC, sblondeau commented on src/View/layout-visitor.html.twig
>  {% extends 'base.html.twig' %}
idem

2019-04-28 21:37 UTC, sblondeau commented on src/View/Reservation/index.html.twig
> +{% extends 'layout-visitor.html.twig' %}
si ta PR gère le add, je ne devrais pas avoir ce fichier dans le commit

2019-04-29 08:54 UTC, lamoureux-sylvain approved these changes

2019-04-29 10:10 UTC, sblondeau requested changes
mes commentaires ne sont pas pris en compte !

2019-04-29 14:59 UTC, dimxpas commented on src/Controller/ReservationController.php
> +    private function checkErrors(array $cleanPost): array
L'email et la date sont maintenant corrigés, le nbPeople est géré depuis le form directement en html impossible de mettre en dessous de 0 et au dessus de 22, l'appointment est un format heure on ne peut que mettre des chiffre sous format horaire

2019-04-29 14:59 UTC, dimxpas commented on .gitignore
> +composer.lock
modifié

2019-04-29 15:00 UTC, dimxpas commented on src/Controller/ReservationController.php
> +                $reservation = [
Modifié

2019-04-29 15:00 UTC, dimxpas commented on src/Controller/ReservationController.php
> +                header('Location:/Reservation/success');
Fait

2019-04-29 20:25 UTC, sblondeau requested changes

2019-04-29 20:25 UTC, sblondeau commented on src/Controller/ReservationController.php
> +    private function checkErrors(array $cleanPost): array
NON ! si c'est très bien de le mettre au niveau du formulaire, mais ça reste coté client et non serveur, donc ça reste modifiable par le visiteurs qui sait utiliser la console du navigateur... et donc faille de sécurité car je peux envoyer ce que je veux, rien n'est vérifié côté serveur. tu
Il faut au moins que ajoute la vérif entre 0 et MAX_PEOPLE (constante à créer) 
et que tu fasse un checkdate sur la date pour etre sur que le format est valide

2019-04-30 08:12 UTC, lamoureux-sylvain approved these changes

2019-04-30 08:19 UTC, sblondeau approved these changes

2019-04-30 08:49 UTC, lamoureux-sylvain approved these changes

2019-04-30 08:54 UTC, merged