Sprint 04 us 27 cards livre d or
WildCodeSchool/orleans-0219-php-dionysos pull request #57
Opened 2019-04-26 15:44 UTC by solennelle

Maj des cards, + responsive, display par ordre d'ajout, affichage de la date

2019-04-26 15:49 UTC, dimxpas approved these changes

2019-04-28 21:41 UTC, sblondeau requested changes

2019-04-28 21:41 UTC, sblondeau commented on src/Model/ReviewManager.php
> +        return $this->pdo->query('SELECT * FROM ' . $this->table .' WHERE LENGTH(name) < 25
euh non là tu ne sélectionner que les enregistrement qui t'arrangent au niveau de l'affichage (moins de XX caractères). Ce n'est pas du tout la bonne façon de s'y prendre. Soit tu limites cette taille à l'insertion, soit tu trouves une solution pour que ça tienne à l'affichage avec plus long (modale, accordion...)

2019-04-28 21:41 UTC, sblondeau commented on src/View/Home/index.html.twig
> +    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css">
pas déjà sur le layout général ? si non ça devrait plutot qu'ici, vu que font-awesome va très certainement servir sur plusieurs pages

2019-04-29 08:48 UTC, dimxpas approved these changes

2019-04-29 08:53 UTC, lamoureux-sylvain approved these changes

2019-04-29 10:11 UTC, sblondeau requested changes

2019-04-29 10:11 UTC, sblondeau commented on src/View/Home/index.html.twig
> +    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css">
tu l'as bien ajouté sur le layout mais du coup il faut le virer ici

2019-04-29 10:15 UTC, solennelle commented
Oops... Corrigé...

2019-04-29 11:49 UTC, lamoureux-sylvain approved these changes

2019-04-29 12:00 UTC, sblondeau approved these changes

2019-04-29 12:00 UTC, merged