Afficher la carte des vins, sans style (qui l'attend dans une autre PR)
WildCodeSchool/orleans-0219-php-dionysos pull request #70
Opened 2019-04-29 15:14 UTC by heagerty

Carte des vins

2019-04-29 15:24 UTC, lamoureux-sylvain approved these changes

2019-04-29 15:25 UTC, lamoureux-sylvain approved these changes

2019-04-29 20:12 UTC, sblondeau requested changes
non ça ne va pas la modélisation de la bdd
il faut une seule table pour les boissons, avec une categorie color pour la couleur du vin. 

De plus, tu ne peux pas avoir une US "sans style" car comme on l'a répété plusieurs fois, le style est une tache incluse dans l'US

2019-05-01 12:33 UTC, lamoureux-sylvain approved these changes

2019-05-01 17:07 UTC, merged