Sprint 04 us 37 accueil cards review
WildCodeSchool/orleans-0219-php-dionysos pull request #74
Opened 2019-04-30 08:04 UTC by solennelle

2019-04-30 08:14 UTC, lamoureux-sylvain approved these changes

2019-04-30 08:22 UTC, sblondeau requested changes

2019-04-30 08:22 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                    <div class="card col-sm-12 col-md-12 col-lg-3 text-center">
c'est exactement le meme code HTML que dans la page review ? dans ce cas déporter le code dans un twig et faire un include dans les 2 pages

2019-04-30 08:32 UTC, solennelle commented on src/View/Home/index.html.twig
> +                    <div class="card col-sm-12 col-md-12 col-lg-3 text-center">
Le html est presque similaire (à quelques classes bootstrap près) mais les variables twig sont différentes.

2019-05-02 07:37 UTC, lamoureux-sylvain approved these changes

2019-05-02 07:46 UTC, sblondeau approved these changes

2019-05-02 07:46 UTC, merged