Sprint02 us08 structure footer
WildCodeSchool/orleans-0219-php-dionysos pull request #9
Opened 2019-04-12 15:31 UTC by dimxpas

Création du footer.

2019-04-12 15:31 UTC, solennelle commented on public/assets/css/style.css
> +.ticketRestau
In english please!

2019-04-12 15:33 UTC, solennelle requested changes
classes CSS en anglais!

2019-04-12 15:35 UTC, solennelle approved these changes

2019-04-12 15:36 UTC, solennelle approved these changes

2019-04-15 08:20 UTC, open-it requested changes

2019-04-15 08:20 UTC, open-it commented on src/View/layout-visitor.html.twig
>  {% block header %} {#include header#} {% endblock %}
pas de code commenté

2019-04-15 08:20 UTC, open-it commented on src/View/layout-visitor.html.twig
> +{% block footer %} {% include 'footer.html.twig' %} {% endblock %}
est ce vraiment utile de faire un block footer ? Allez vous rajouter quelque chose dans le footer via les vues  ? (Je ne pense pas)

2019-04-15 08:50 UTC, heagerty commented on src/View/layout-visitor.html.twig
>  {% block header %} {#include header#} {% endblock %}
code commenté a été supprimé

2019-04-15 08:51 UTC, heagerty commented on src/View/layout-visitor.html.twig
> +{% block footer %} {% include 'footer.html.twig' %} {% endblock %}
t'as raison !  ;-)
block footer remplacé par footer.

2019-04-15 08:52 UTC, heagerty approved these changes
Corrections effectuées. En attendant revue par le formateur...

2019-04-15 09:26 UTC, open-it approved these changes

2019-04-15 09:27 UTC, merged